locals {
  resource_prefix = coalesce(var.prefix, var.experiment_name)
  cluster_name    = local.resource_prefix
  node_tag        = "${local.resource_prefix}-node"

  common_labels = merge(var.labels, {
    experiment = var.experiment_name
    managed-by = "terraform"
  })

  ssh_private_key_path = coalesce(
    var.ssh_private_key_path,
    trimsuffix(var.ssh_public_key_path, ".pub"),
  )

  resolved_source_image = var.source_image != null ? var.source_image : data.google_compute_image.ubuntu[0].self_link

  ops_bootstrap_template_path = "${path.module}/templates/bootstrap-ops.sh.tftpl"
  ops_bootstrap_revision = sha256(join("|", [
    filesha256(local.ops_bootstrap_template_path),
    var.kubernetes_minor_version,
    var.kubernetes_apt_version,
    var.cilium_cli_version,
  ]))
}

data "google_compute_network" "vpc" {
  provider = google-beta
  name     = var.network_name
  project  = var.project_id
}

data "google_compute_subnetwork" "subnet" {
  provider = google-beta
  name     = var.subnetwork_name
  project  = var.project_id
  region   = var.region
}

data "google_compute_image" "ubuntu" {
  provider = google-beta
  count    = var.source_image == null ? 1 : 0
  family   = var.source_image_family
  project  = var.source_image_project
}

resource "google_compute_resource_policy" "compact" {
  provider    = google-beta
  name        = "${local.resource_prefix}-compact"
  project     = var.project_id
  region      = var.region
  description = "Compact placement policy for the ${upper(var.experiment_name)} (GKE) experiment."

  group_placement_policy {
    collocation = "COLLOCATED"

    # max_distance is deliberately not set here (the kubeadm methods use
    # max_distance=1). A collocated policy with max_distance forbids live
    # migration, but GKE NodeConfig has no way to set onHostMaintenance to
    # TERMINATE, so nodes are always created with MIGRATE. The two constraints
    # conflict and the node pool fails to create, landing in ERROR:
    #   - collocated + max_distance=1 + MIGRATE -> rejected (reproduced)
    #   - collocated + no max_distance + MIGRATE -> created successfully
    # So only collocation is applied here and TERMINATE is set after T5 with
    # set-scheduling. The real physical placement is verified by the
    # control-vars step of provision-gke.ps1 through resourceStatus.physicalHost.
  }

  lifecycle {
    precondition {
      condition     = var.expected_subnet_cidr == null || data.google_compute_subnetwork.subnet.ip_cidr_range == var.expected_subnet_cidr
      error_message = "Subnet CIDR mismatch: subnet '${var.subnetwork_name}' is ${data.google_compute_subnetwork.subnet.ip_cidr_range}, expected ${coalesce(var.expected_subnet_cidr, "null")}."
    }
  }
}

# For ops VM SSH. The GKE nodes carry the same tag so they can be reached over
# SSH when needed. Node-to-node and pod firewall rules are generated by GKE
# itself (gke-<cluster>-*) and are not created here.
resource "google_compute_firewall" "ssh" {
  provider  = google-beta
  name      = "${local.resource_prefix}-allow-ssh"
  project   = var.project_id
  network   = data.google_compute_network.vpc.self_link
  direction = "INGRESS"

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = var.ssh_source_ranges
  target_tags   = [local.node_tag]
}

resource "google_container_cluster" "cluster" {
  provider = google-beta
  name     = local.cluster_name
  project  = var.project_id
  location = var.zone # zonal cluster

  network    = data.google_compute_network.vpc.self_link
  subnetwork = data.google_compute_subnetwork.subnet.self_link

  # New GKE customers must enroll clusters in a release channel. The requested
  # exact creation version must be offered by REGULAR in this zone.
  min_master_version = var.gke_version
  release_channel {
    channel = "REGULAR"
  }

  # The essence of N-Cloud: VPC-native (Alias IP). Dataplane V2 = managed Cilium.
  networking_mode   = "VPC_NATIVE"
  datapath_provider = "ADVANCED_DATAPATH"

  ip_allocation_policy {
    cluster_ipv4_cidr_block  = var.pod_cidr
    services_ipv4_cidr_block = var.services_cidr
  }

  # 110 pods/node makes GKE assign a /24 Pod CIDR per node, as in kubeadm.
  default_max_pods_per_node = var.max_pods_per_node

  # Node pools are managed only by the resources below; the temporary default pool is removed at once.
  remove_default_node_pool = true
  initial_node_count       = 1

  # Required for destroy: terraform destroy fails while this is true.
  deletion_protection = false

  # Minimizes measurement noise: no logging or monitoring agent is deployed.
  # (The GCP infrastructure metrics are hypervisor level and are unaffected.)
  logging_service    = "none"
  monitoring_service = "none"

  resource_labels = local.common_labels
}

resource "google_container_node_pool" "bench" {
  provider = google-beta
  name     = "bench"
  project  = var.project_id
  cluster  = google_container_cluster.cluster.name
  location = var.zone

  version    = var.gke_version
  node_count = 1

  # Requirement: no node recreation or version change during experiments 2 and 3.
  management {
    auto_repair  = false
    auto_upgrade = false
  }

  placement_policy {
    type        = "COMPACT"
    policy_name = google_compute_resource_policy.compact.name
  }

  # Values recommended by the GKE compact placement documentation
  # (--max-surge-upgrade 0 / --max-unavailable-upgrade N): they raise "the
  # likelihood of finding colocated nodes during upgrades". A surge node is an
  # extra temporary VM that has to join the placement group and can break
  # collocation. auto_upgrade=false means no upgrade happens on its own, but the
  # recommended values are set so placement stays consistent even during a
  # forced upgrade. The strategy is fixed to SURGE (a user-defined policy does
  # not support blue-green upgrades).
  upgrade_settings {
    strategy        = "SURGE"
    max_surge       = 0
    max_unavailable = 1
  }

  node_config {
    machine_type     = var.machine_type
    min_cpu_platform = var.min_cpu_platform
    image_type       = "UBUNTU_CONTAINERD"
    disk_type        = "pd-balanced"
    disk_size_gb     = var.disk_size_gb
    service_account  = var.service_account_email
    oauth_scopes     = var.service_account_scopes
    tags             = [local.node_tag]

    labels = {
      experiment-role = "benchmark"
    }

    # The benchmark node is tainted so ordinary pods cannot be scheduled on it.
    # Unlike kubeadm, the node pool definition applies it from creation time.
    taint {
      key    = "benchmark-only"
      value  = "true"
      effect = "NO_SCHEDULE"
    }

    # ssh-keys is not on the reserved key list of GKE NodeConfig, so it can be
    # injected (confirmed through API discovery). The experiment 3 clock offset
    # measurement SSHes into the bench node, so it gets the same key as the ops
    # VM; that is narrower in scope than registering the key in the
    # project-wide metadata. (enable-oslogin is reserved and is not set here:
    # the project default of OS Login disabled is used as is.)
    metadata = {
      disable-legacy-endpoints = "true"
      ssh-keys                 = "${var.ssh_user}:${trimspace(file(var.ssh_public_key_path))}"
    }
  }
}

resource "google_container_node_pool" "worker" {
  provider = google-beta
  name     = "worker"
  project  = var.project_id
  cluster  = google_container_cluster.cluster.name
  location = var.zone

  version = var.gke_version
  # 4->8 expansion: applying worker_count 2 -> 6 on the same state resizes only this pool.
  node_count = var.worker_count

  management {
    auto_repair  = false
    auto_upgrade = false
  }

  placement_policy {
    type        = "COMPACT"
    policy_name = google_compute_resource_policy.compact.name
  }

  # Same reason as the bench pool (the documented fast no-surge upgrade).
  # max_unavailable follows the pool size, so it becomes 6 during the expansion.
  upgrade_settings {
    strategy        = "SURGE"
    max_surge       = 0
    max_unavailable = var.worker_count
  }

  node_config {
    machine_type     = var.machine_type
    min_cpu_platform = var.min_cpu_platform
    image_type       = "UBUNTU_CONTAINERD"
    disk_type        = "pd-balanced"
    disk_size_gb     = var.disk_size_gb
    service_account  = var.service_account_email
    oauth_scopes     = var.service_account_scopes
    tags             = [local.node_tag]

    labels = {
      experiment-role = "worker"
    }

    # ssh-keys is not on the reserved key list of GKE NodeConfig, so it can be
    # injected (confirmed through API discovery). The experiment 3 clock offset
    # measurement SSHes into the bench node, so it gets the same key as the ops
    # VM; that is narrower in scope than registering the key in the
    # project-wide metadata. (enable-oslogin is reserved and is not set here:
    # the project default of OS Login disabled is used as is.)
    metadata = {
      disable-legacy-endpoints = "true"
      ssh-keys                 = "${var.ssh_user}:${trimspace(file(var.ssh_public_key_path))}"
    }
  }
}

# ops VM for experiments 2 and 3: it plays the orchestration/timing role the CP
# VM plays elsewhere and is not a cluster member. It is not part of the measured
# apply (it is created afterwards with -var=create_ops_vm=true), and the plan
# guard of the provisioning script asserts the measured plan contains no change
# to this resource. Creating it after the cluster keeps it from taking a
# compact-policy sub-block first.
resource "google_compute_instance" "ops" {
  provider = google-beta
  count    = var.create_ops_vm ? 1 : 0

  name             = "${local.resource_prefix}-ops-0"
  project          = var.project_id
  zone             = var.zone
  machine_type     = var.ops_machine_type
  min_cpu_platform = var.min_cpu_platform

  # Same physical rack (sub-block) as the nodes. Attached at creation, so no stop/start is needed.
  resource_policies = [
    google_compute_resource_policy.compact.self_link
  ]

  tags = [local.node_tag]

  labels = merge(local.common_labels, {
    role = "ops"
  })

  boot_disk {
    auto_delete = true

    initialize_params {
      image = local.resolved_source_image
      size  = var.ops_disk_size_gb
      type  = "pd-balanced"

      labels = merge(local.common_labels, {
        role = "ops"
      })
    }
  }

  network_interface {
    network    = data.google_compute_network.vpc.self_link
    subnetwork = data.google_compute_subnetwork.subnet.self_link

    access_config {
      network_tier = "PREMIUM"
    }
  }

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "TERMINATE" # an ordinary Compute VM, so it is set at creation
    provisioning_model  = "STANDARD"
  }

  metadata = {
    enable-oslogin         = "FALSE"
    ssh-keys               = "${var.ssh_user}:${trimspace(file(var.ssh_public_key_path))}"
    experiment-name        = var.experiment_name
    experiment-role        = "ops"
    ops-bootstrap-revision = local.ops_bootstrap_revision
  }

  metadata_startup_script = replace(
    "${templatefile(local.ops_bootstrap_template_path, {
      kubernetes_minor_version = var.kubernetes_minor_version
      kubernetes_apt_version   = var.kubernetes_apt_version
      cilium_cli_version       = var.cilium_cli_version
      bootstrap_revision       = local.ops_bootstrap_revision
      ssh_user                 = var.ssh_user
    })}\n# ops-bootstrap-revision: ${local.ops_bootstrap_revision}\n",
    "\r\n", "\n"
  )

  dynamic "service_account" {
    for_each = var.service_account_email == null ? [] : [var.service_account_email]
    content {
      email  = service_account.value
      scopes = var.service_account_scopes
    }
  }

  # Forces creation after the cluster and node pools (so no sub-block is taken first).
  depends_on = [
    google_container_node_pool.bench,
    google_container_node_pool.worker,
  ]

  lifecycle {
    # ssh-keys: console/browser SSH can append a temporary key.
    # boot_disk: source_image resolves a family, so a newly published Ubuntu
    # image creates a replacement diff, which would fail the measured plan guard
    # of the 8-node expansion (its no-delete rule). Image drift after creation
    # is ignored.
    ignore_changes = [
      metadata["ssh-keys"],
      boot_disk,
    ]
  }
}
